### ISSUE TITLE
infamous Python+libtcod tutorial?

### ISSUE THREAD

**Issue by anmej** [tomassedovic/roguelike-tutorial#1]
Infamous usually means bad. :-) Did you mean famous, perhaps?

**Comment by tomassedovic** [comment]
Thanks. I actually meant to write "(in)famous" :-).

The tutorial is great, but people who start with it tend to produce games that are quite similar. Just adding new monsters, spells and items and not much more.

Plus I've seen a lot of criticism of the code. Not necessarily a fair criticism -- it's optimised for ease of teaching & learning rather than for any best practices. But still -- it's not universally accepted as a force of good.

I plan to acknowledge both when I get to write the actual text.
